### ISSUE TITLE
How to define the 'contents' property?

### ISSUE THREAD

**Issue by glebfox** [electron-userland/electron-installer-dmg#22]
I want to change coordinates of Applications link and app icon, but I can't figure out how to solve this issue. 

Thanks in advance.

**Comment by jay0lu** [comment]
I have the same question, any solutions?

**Comment by mnaamani** [comment]
You should be able to add a contents property to your config section `electronInstallerDMG` of the package.json

```
"electronInstallerDMG": {
    "contents": [
    {
      x: 700,
      y: 350,
      type: 'link',
      path: '/Applications'
    },
    {
      x: 220,
      y: 350,
      type: 'file',
      path: '/path/to/app.dmg')
    }]
  }
```

**Comment by lucasbento** [comment]
@mnaamani: tried that and partly worked, how do I get the `path` of my app without having it hard-coded? Basically I need the default value of `opts.appPath` that's being used here: https://github.com/mongodb-js/electron-installer-dmg/blob/master/index.js#L68.

**Comment by mnaamani** [comment]
Unfortunately there isn't a way to grab that value. What I ended up doing was moving my forge config from the package.json into a `.js` file. 

Like this:
the config section in my `package.json`
```
"config": {
    "forge": "./forge-config.js"
  }
```

and the forge-config.js is basically an export of the config object.. this gives you some flexibility to compute the path value rather than hardcoding a string in the package.json

```
module.exports = {
    .
    .
   "electronInstallerDMG": {
        contents: [
         ....
        ]
    },
    .
    .
}
```

**Comment by mnaamani** [comment]
I suppose if you have a global variable in the forge-config.js you can reuse it throughout the configuration section?

Or better yet maybe you can use templated variable names? https://electronforge.io/config/extra/templating

**Comment by mnaamani** [comment]
What would be really nice is to have electron-installer-dmg accept a function that gets called with the opts so we can define the contents property as:
```
function (opts) {
    // return the contents array
    return ([
         {
            path: opts.appPath  // so we can use the appPath option
         },
     ])
}
```

**Comment by lucasbento** [comment]
> What would be really nice is to have electron-installer-dmg accept a function that gets called with the opts.

Thought about the same, I would gladly work on a PR for that.

cc @imlucas (nice name, btw), maybe you have an opinion on this.

**Comment by mnaamani** [comment]
Simplest implementation just to illustrate: https://github.com/mongodb-js/electron-installer-dmg/pull/25

**Comment by lucasbento** [comment]
@mnaamani: awesome!

**Comment by MarshallOfSound** [comment]
Fixed in #25

**Comment by appar-sc** [comment]
Just figured can use `"/Volumes/DMG_NAME/MY_APP.app"`

```
...
    "contents": [
              {
                "x": 100,
                "y": 350,
                "type": "link",
                "path": "/Applications"
              },
              {
                "x": 220,
                "y": 350,
                "type": "file",
                "path": "/Volumes/DMG_NAME/MY_APP.app"
              }
            ]
...

```

**Comment by JasinYip** [comment]
This issue killed 2 hours of my life...

It would be helpful for users if this solution could add into the user guide.
