### ISSUE TITLE
feature /help to per or post install script execute

### ISSUE THREAD

**Issue by dipenpatel235** [electron-userland/electron-installer-dmg#27]
hello..
i am looking for this feature if we can do or any help.

actually after create dmg i required to copy some file on some location so if inside dmg after execute that script so something good.

but i don't know about mac.

so if youkanow anything or you can implement in this so something good.

Thanks
Dipen

**Comment by MarshallOfSound** [comment]
macOS has no concept of "install" and "uninstall", you should track "first run" from your app and run your logic there.  A common practice is to use some kind of tracker file that you create when your app is run, if the file isn't there your app has not been run before 👍
